### ISSUE TITLE
PWA/Service Worker Compatibility

### ISSUE THREAD

**Issue by jayoma** [DanWahlin/Angular-Docker-Microservices#4]
I'm attempting to use your nginx.conf to host an Angular PWA/service worker project via Docker.

What I'm finding is that the app does not properly leverage the service worker when hosting through my container.

When I follow the [Angular docs](https://angular.io/guide/service-worker-getting-started) to serve the app with http-server, the service worker properly intercepts the requests and serves the resources from the cache. I can also load the app when http-server is not running, once the service worker has previously cached the resources. So basically.. it's behaving exactly as I would expect a service worker to behave:

<img width="852" alt="ServiceWorkerWorking" src="https://user-images.githubusercontent.com/3663759/63536138-d144e500-c4c7-11e9-8bfc-b11741a22cac.PNG">

When I host the exact same service worker build through my Docker container/NGINX, however, the app behaves much differently:

<img width="944" alt="ServiceWorkerNotWorking" src="https://user-images.githubusercontent.com/3663759/63536412-6516b100-c4c8-11e9-8bd5-9b08bc0baa47.PNG">

Furthermore, when I take my container down, I can no longer load the app from the service worker's cache. The only real difference here is that I'm hosting through a Docker container, but more specifically, through NGINX.

So my question is: what changes do I need to make to my nginx.conf in order to make NGINX play nicely with a PWA/service worker setup?

**Comment by DanWahlin** [comment]
Hi Jason. I've never tried using service workers from a container so I don't have any answer for you unfortunately. With a normal Angular app you just have to make sure routes redirect to your "index.html" homepage (whatever that is for a given app) as shown in this config file:

https://github.com/DanWahlin/Angular-Core-Concepts/blob/master/config/nginx.conf#L18

I'm guessing you have that in your config already though.

The best I can recommend is to post as much detail as possible to StackOverflow to see if someone has run into that. Wish I had more details there for you - just not something I'm working with right now though.

**Comment by jayoma** [comment]
@DanWahlin Thanks for your reply! I'll post back here if/when I get it working.

**Comment by dassudip2001** [comment]
Any solution available
